version: "3.7"

services:
  zoo1:
    image: zookeeper
    restart: unless-stopped
    hostname: localhost
    ports:
      - "2181:2181"
    container_name: zookeeper

  kafka1:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "stream-in:1:1,stream-out:1:1"
    depends_on:
      - zoo1
    container_name: kafka

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    container_name:
      redis
    command: redis-server

  jenkins:
    images: jenkins/jenkins
    restart: always
    ports:
      - "10080:8080"
    container_name:
      jenkins


